# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_mw.ui'
#
# Created: Wed May 28 15:33:34 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1026, 867)
        font = QtGui.QFont()
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Window/Icon_Sci_Corpus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonSentenceRemove = QtGui.QPushButton(self.widget)
        self.pushButtonSentenceRemove.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonSentenceRemove.setObjectName("pushButtonSentenceRemove")
        self.gridLayout_2.addWidget(self.pushButtonSentenceRemove, 4, 4, 1, 1)
        self.labelReference = QtGui.QLabel(self.widget)
        self.labelReference.setObjectName("labelReference")
        self.gridLayout_2.addWidget(self.labelReference, 4, 0, 1, 1)
        self.pushButtonSentenceUpdate = QtGui.QPushButton(self.widget)
        self.pushButtonSentenceUpdate.setMaximumSize(QtCore.QSize(85, 16777215))
        self.pushButtonSentenceUpdate.setObjectName("pushButtonSentenceUpdate")
        self.gridLayout_2.addWidget(self.pushButtonSentenceUpdate, 4, 5, 1, 1)
        self.lineEditReference = QtGui.QLineEdit(self.widget)
        self.lineEditReference.setObjectName("lineEditReference")
        self.gridLayout_2.addWidget(self.lineEditReference, 4, 1, 1, 1)
        self.pushButtonSentenceAdd = QtGui.QPushButton(self.widget)
        self.pushButtonSentenceAdd.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonSentenceAdd.setObjectName("pushButtonSentenceAdd")
        self.gridLayout_2.addWidget(self.pushButtonSentenceAdd, 4, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 17))
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.textEditSentence = QtGui.QTextEdit(self.widget)
        self.textEditSentence.setMinimumSize(QtCore.QSize(0, 0))
        self.textEditSentence.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textEditSentence.setObjectName("textEditSentence")
        self.gridLayout_2.addWidget(self.textEditSentence, 1, 0, 1, 6)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1026, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSection = QtGui.QMenu(self.menubar)
        self.menuSection.setObjectName("menuSection")
        self.menuComponent = QtGui.QMenu(self.menubar)
        self.menuComponent.setObjectName("menuComponent")
        self.menuStrategy = QtGui.QMenu(self.menubar)
        self.menuStrategy.setObjectName("menuStrategy")
        self.menuSentence = QtGui.QMenu(self.menubar)
        self.menuSentence.setObjectName("menuSentence")
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidgetSection = QtGui.QDockWidget(MainWindow)
        self.dockWidgetSection.setObjectName("dockWidgetSection")
        self.dockWidgetContentsSection = QtGui.QWidget()
        self.dockWidgetContentsSection.setObjectName("dockWidgetContentsSection")
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContentsSection)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonSectionRemove = QtGui.QPushButton(self.dockWidgetContentsSection)
        self.pushButtonSectionRemove.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonSectionRemove.setObjectName("pushButtonSectionRemove")
        self.gridLayout.addWidget(self.pushButtonSectionRemove, 0, 2, 1, 1)
        self.lineEditSection = QtGui.QLineEdit(self.dockWidgetContentsSection)
        self.lineEditSection.setText("")
        self.lineEditSection.setObjectName("lineEditSection")
        self.gridLayout.addWidget(self.lineEditSection, 0, 0, 1, 1)
        self.pushButtonSectionAdd = QtGui.QPushButton(self.dockWidgetContentsSection)
        self.pushButtonSectionAdd.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonSectionAdd.setObjectName("pushButtonSectionAdd")
        self.gridLayout.addWidget(self.pushButtonSectionAdd, 0, 1, 1, 1)
        self.pushButtonSectionUpdate = QtGui.QPushButton(self.dockWidgetContentsSection)
        self.pushButtonSectionUpdate.setObjectName("pushButtonSectionUpdate")
        self.gridLayout.addWidget(self.pushButtonSectionUpdate, 0, 3, 1, 1)
        self.listWidgetSection = QtGui.QListWidget(self.dockWidgetContentsSection)
        self.listWidgetSection.setMinimumSize(QtCore.QSize(0, 100))
        self.listWidgetSection.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidgetSection.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.listWidgetSection.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listWidgetSection.setAlternatingRowColors(False)
        self.listWidgetSection.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidgetSection.setMovement(QtGui.QListView.Free)
        self.listWidgetSection.setViewMode(QtGui.QListView.ListMode)
        self.listWidgetSection.setModelColumn(0)
        self.listWidgetSection.setUniformItemSizes(False)
        self.listWidgetSection.setSelectionRectVisible(True)
        self.listWidgetSection.setObjectName("listWidgetSection")
        self.gridLayout.addWidget(self.listWidgetSection, 1, 0, 1, 4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(self.dockWidgetContentsSection)
        self.label.setStyleSheet("color: rgb(111, 111, 111);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.labelSelectedSection = QtGui.QLabel(self.dockWidgetContentsSection)
        self.labelSelectedSection.setStyleSheet("color: rgb(111, 111, 111);")
        self.labelSelectedSection.setObjectName("labelSelectedSection")
        self.horizontalLayout.addWidget(self.labelSelectedSection)
        self.label_3 = QtGui.QLabel(self.dockWidgetContentsSection)
        self.label_3.setStyleSheet("color: rgb(111, 111, 111);")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.labelHighlightedSection = QtGui.QLabel(self.dockWidgetContentsSection)
        self.labelHighlightedSection.setStyleSheet("color: rgb(111, 111, 111);")
        self.labelHighlightedSection.setObjectName("labelHighlightedSection")
        self.horizontalLayout.addWidget(self.labelHighlightedSection)
        self.label_2 = QtGui.QLabel(self.dockWidgetContentsSection)
        self.label_2.setStyleSheet("color: rgb(111, 111, 111);")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.labelTotalSection = QtGui.QLabel(self.dockWidgetContentsSection)
        self.labelTotalSection.setStyleSheet("color: rgb(111, 111, 111);")
        self.labelTotalSection.setObjectName("labelTotalSection")
        self.horizontalLayout.addWidget(self.labelTotalSection)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 3, 4)
        self.line_3 = QtGui.QFrame(self.dockWidgetContentsSection)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 6, 0, 1, 4)
        self.dockWidgetSection.setWidget(self.dockWidgetContentsSection)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidgetSection)
        self.dockWidgetComponent = QtGui.QDockWidget(MainWindow)
        self.dockWidgetComponent.setObjectName("dockWidgetComponent")
        self.dockWidgetContentsComponent = QtGui.QWidget()
        self.dockWidgetContentsComponent.setObjectName("dockWidgetContentsComponent")
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContentsComponent)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEditComponent = QtGui.QLineEdit(self.dockWidgetContentsComponent)
        self.lineEditComponent.setObjectName("lineEditComponent")
        self.gridLayout_3.addWidget(self.lineEditComponent, 0, 0, 1, 1)
        self.pushButtonComponentAdd = QtGui.QPushButton(self.dockWidgetContentsComponent)
        self.pushButtonComponentAdd.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonComponentAdd.setObjectName("pushButtonComponentAdd")
        self.gridLayout_3.addWidget(self.pushButtonComponentAdd, 0, 1, 1, 1)
        self.pushButtonComponentRemove = QtGui.QPushButton(self.dockWidgetContentsComponent)
        self.pushButtonComponentRemove.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonComponentRemove.setObjectName("pushButtonComponentRemove")
        self.gridLayout_3.addWidget(self.pushButtonComponentRemove, 0, 2, 1, 1)
        self.pushButtonComponentUpdate = QtGui.QPushButton(self.dockWidgetContentsComponent)
        self.pushButtonComponentUpdate.setObjectName("pushButtonComponentUpdate")
        self.gridLayout_3.addWidget(self.pushButtonComponentUpdate, 0, 3, 1, 1)
        self.listWidgetComponent = QtGui.QListWidget(self.dockWidgetContentsComponent)
        self.listWidgetComponent.setMinimumSize(QtCore.QSize(0, 100))
        self.listWidgetComponent.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidgetComponent.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.listWidgetComponent.setAlternatingRowColors(False)
        self.listWidgetComponent.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidgetComponent.setMovement(QtGui.QListView.Free)
        self.listWidgetComponent.setSelectionRectVisible(True)
        self.listWidgetComponent.setObjectName("listWidgetComponent")
        self.gridLayout_3.addWidget(self.listWidgetComponent, 1, 0, 1, 4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_7 = QtGui.QLabel(self.dockWidgetContentsComponent)
        self.label_7.setStyleSheet("color: rgb(111, 111, 111);")
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.labelSelectedComponent = QtGui.QLabel(self.dockWidgetContentsComponent)
        self.labelSelectedComponent.setStyleSheet("color: rgb(111, 111, 111);")
        self.labelSelectedComponent.setObjectName("labelSelectedComponent")
        self.horizontalLayout_2.addWidget(self.labelSelectedComponent)
        self.label_9 = QtGui.QLabel(self.dockWidgetContentsComponent)
        self.label_9.setStyleSheet("color: rgb(111, 111, 111);")
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.labelHighlightedComponent = QtGui.QLabel(self.dockWidgetContentsComponent)
        self.labelHighlightedComponent.setStyleSheet("color: rgb(111, 111, 111);")
        self.labelHighlightedComponent.setObjectName("labelHighlightedComponent")
        self.horizontalLayout_2.addWidget(self.labelHighlightedComponent)
        self.label_8 = QtGui.QLabel(self.dockWidgetContentsComponent)
        self.label_8.setStyleSheet("color: rgb(111, 111, 111);")
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.labelTotalComponent = QtGui.QLabel(self.dockWidgetContentsComponent)
        self.labelTotalComponent.setStyleSheet("color: rgb(111, 111, 111);")
        self.labelTotalComponent.setObjectName("labelTotalComponent")
        self.horizontalLayout_2.addWidget(self.labelTotalComponent)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 2, 4)
        self.line_2 = QtGui.QFrame(self.dockWidgetContentsComponent)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 4, 0, 1, 4)
        self.dockWidgetComponent.setWidget(self.dockWidgetContentsComponent)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidgetComponent)
        self.dockWidgetStrategy = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetStrategy.sizePolicy().hasHeightForWidth())
        self.dockWidgetStrategy.setSizePolicy(sizePolicy)
        self.dockWidgetStrategy.setObjectName("dockWidgetStrategy")
        self.dockWidgetContentsStrategy = QtGui.QWidget()
        self.dockWidgetContentsStrategy.setObjectName("dockWidgetContentsStrategy")
        self.gridLayout_4 = QtGui.QGridLayout(self.dockWidgetContentsStrategy)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEditStrategy = QtGui.QLineEdit(self.dockWidgetContentsStrategy)
        self.lineEditStrategy.setObjectName("lineEditStrategy")
        self.gridLayout_4.addWidget(self.lineEditStrategy, 0, 0, 1, 1)
        self.pushButtonStrategyAdd = QtGui.QPushButton(self.dockWidgetContentsStrategy)
        self.pushButtonStrategyAdd.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonStrategyAdd.setObjectName("pushButtonStrategyAdd")
        self.gridLayout_4.addWidget(self.pushButtonStrategyAdd, 0, 1, 1, 1)
        self.pushButtonStrategyRemove = QtGui.QPushButton(self.dockWidgetContentsStrategy)
        self.pushButtonStrategyRemove.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonStrategyRemove.setObjectName("pushButtonStrategyRemove")
        self.gridLayout_4.addWidget(self.pushButtonStrategyRemove, 0, 2, 1, 1)
        self.pushButtonStrategyUpdate = QtGui.QPushButton(self.dockWidgetContentsStrategy)
        self.pushButtonStrategyUpdate.setObjectName("pushButtonStrategyUpdate")
        self.gridLayout_4.addWidget(self.pushButtonStrategyUpdate, 0, 3, 1, 1)
        self.listWidgetStrategy = QtGui.QListWidget(self.dockWidgetContentsStrategy)
        self.listWidgetStrategy.setMinimumSize(QtCore.QSize(0, 100))
        self.listWidgetStrategy.setMidLineWidth(0)
        self.listWidgetStrategy.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.listWidgetStrategy.setAlternatingRowColors(False)
        self.listWidgetStrategy.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidgetStrategy.setMovement(QtGui.QListView.Free)
        self.listWidgetStrategy.setSelectionRectVisible(True)
        self.listWidgetStrategy.setObjectName("listWidgetStrategy")
        self.gridLayout_4.addWidget(self.listWidgetStrategy, 1, 0, 1, 4)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_14 = QtGui.QLabel(self.dockWidgetContentsStrategy)
        self.label_14.setStyleSheet("color: rgb(111, 111, 111);")
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_4.addWidget(self.label_14)
        self.labelSelectedStrategy = QtGui.QLabel(self.dockWidgetContentsStrategy)
        self.labelSelectedStrategy.setStyleSheet("color: rgb(111, 111, 111);")
        self.labelSelectedStrategy.setObjectName("labelSelectedStrategy")
        self.horizontalLayout_4.addWidget(self.labelSelectedStrategy)
        self.label_15 = QtGui.QLabel(self.dockWidgetContentsStrategy)
        self.label_15.setStyleSheet("color: rgb(111, 111, 111);")
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        self.labelHighlightedStrategy = QtGui.QLabel(self.dockWidgetContentsStrategy)
        self.labelHighlightedStrategy.setStyleSheet("color: rgb(111, 111, 111);")
        self.labelHighlightedStrategy.setObjectName("labelHighlightedStrategy")
        self.horizontalLayout_4.addWidget(self.labelHighlightedStrategy)
        self.label_17 = QtGui.QLabel(self.dockWidgetContentsStrategy)
        self.label_17.setStyleSheet("color: rgb(111, 111, 111);")
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.labelTotalStrategy = QtGui.QLabel(self.dockWidgetContentsStrategy)
        self.labelTotalStrategy.setStyleSheet("color: rgb(111, 111, 111);")
        self.labelTotalStrategy.setObjectName("labelTotalStrategy")
        self.horizontalLayout_4.addWidget(self.labelTotalStrategy)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 2, 0, 1, 4)
        self.line = QtGui.QFrame(self.dockWidgetContentsStrategy)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 3, 0, 1, 4)
        self.dockWidgetStrategy.setWidget(self.dockWidgetContentsStrategy)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidgetStrategy)
        self.dockWidgetTableView = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetTableView.sizePolicy().hasHeightForWidth())
        self.dockWidgetTableView.setSizePolicy(sizePolicy)
        self.dockWidgetTableView.setObjectName("dockWidgetTableView")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_5 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.checkBoxReference = QtGui.QCheckBox(self.dockWidgetContents_2)
        self.checkBoxReference.setObjectName("checkBoxReference")
        self.gridLayout_5.addWidget(self.checkBoxReference, 0, 4, 1, 1)
        self.checkBoxStrip = QtGui.QCheckBox(self.dockWidgetContents_2)
        self.checkBoxStrip.setChecked(True)
        self.checkBoxStrip.setObjectName("checkBoxStrip")
        self.gridLayout_5.addWidget(self.checkBoxStrip, 0, 6, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 7, 1, 1)
        self.checkBoxSection = QtGui.QCheckBox(self.dockWidgetContents_2)
        self.checkBoxSection.setObjectName("checkBoxSection")
        self.gridLayout_5.addWidget(self.checkBoxSection, 0, 0, 1, 1)
        self.checkBoxStrategy = QtGui.QCheckBox(self.dockWidgetContents_2)
        self.checkBoxStrategy.setObjectName("checkBoxStrategy")
        self.gridLayout_5.addWidget(self.checkBoxStrategy, 0, 2, 1, 1)
        self.checkBoxComponent = QtGui.QCheckBox(self.dockWidgetContents_2)
        self.checkBoxComponent.setObjectName("checkBoxComponent")
        self.gridLayout_5.addWidget(self.checkBoxComponent, 0, 1, 1, 1)
        self.checkBoxSentence = QtGui.QCheckBox(self.dockWidgetContents_2)
        self.checkBoxSentence.setChecked(True)
        self.checkBoxSentence.setObjectName("checkBoxSentence")
        self.gridLayout_5.addWidget(self.checkBoxSentence, 0, 3, 1, 1)
        self.line_4 = QtGui.QFrame(self.dockWidgetContents_2)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_5.addWidget(self.line_4, 0, 5, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_4.setStyleSheet("color: rgb(111, 111, 111);")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.labelSelectedSentence = QtGui.QLabel(self.dockWidgetContents_2)
        self.labelSelectedSentence.setStyleSheet("color: rgb(111, 111, 111);")
        self.labelSelectedSentence.setObjectName("labelSelectedSentence")
        self.horizontalLayout_3.addWidget(self.labelSelectedSentence)
        self.label_6 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_6.setStyleSheet("color: rgb(111, 111, 111);")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.labelHighlightedSentence = QtGui.QLabel(self.dockWidgetContents_2)
        self.labelHighlightedSentence.setStyleSheet("color: rgb(111, 111, 111);")
        self.labelHighlightedSentence.setObjectName("labelHighlightedSentence")
        self.horizontalLayout_3.addWidget(self.labelHighlightedSentence)
        self.label_11 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_11.setStyleSheet("color: rgb(111, 111, 111);")
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.labelTotalSentence = QtGui.QLabel(self.dockWidgetContents_2)
        self.labelTotalSentence.setStyleSheet("color: rgb(111, 111, 111);")
        self.labelTotalSentence.setObjectName("labelTotalSentence")
        self.horizontalLayout_3.addWidget(self.labelTotalSentence)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 0, 8, 1, 1)
        self.tableWidgetSentence = QtGui.QTableWidget(self.dockWidgetContents_2)
        self.tableWidgetSentence.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidgetSentence.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetSentence.setDragDropOverwriteMode(False)
        self.tableWidgetSentence.setAlternatingRowColors(True)
        self.tableWidgetSentence.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetSentence.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.tableWidgetSentence.setObjectName("tableWidgetSentence")
        self.tableWidgetSentence.setColumnCount(0)
        self.tableWidgetSentence.setRowCount(0)
        self.tableWidgetSentence.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetSentence.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidgetSentence.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetSentence.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidgetSentence.verticalHeader().setSortIndicatorShown(True)
        self.tableWidgetSentence.verticalHeader().setStretchLastSection(False)
        self.gridLayout_5.addWidget(self.tableWidgetSentence, 2, 0, 1, 9)
        self.dockWidgetTableView.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidgetTableView)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidgetLogView = QtGui.QDockWidget(MainWindow)
        self.dockWidgetLogView.setObjectName("dockWidgetLogView")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_6 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButtonClearLog = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButtonClearLog.setMaximumSize(QtCore.QSize(85, 16777215))
        self.pushButtonClearLog.setObjectName("pushButtonClearLog")
        self.gridLayout_6.addWidget(self.pushButtonClearLog, 0, 0, 1, 1)
        self.textEditLogView = QtGui.QTextEdit(self.dockWidgetContents)
        self.textEditLogView.setEnabled(True)
        self.textEditLogView.setStyleSheet("color: rgb(85, 170, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.textEditLogView.setAutoFormatting(QtGui.QTextEdit.AutoBulletList)
        self.textEditLogView.setUndoRedoEnabled(False)
        self.textEditLogView.setReadOnly(True)
        self.textEditLogView.setObjectName("textEditLogView")
        self.gridLayout_6.addWidget(self.textEditLogView, 1, 0, 1, 1)
        self.dockWidgetLogView.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidgetLogView)
        self.actionOpen = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/File/document-open-7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/File/document-save-3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/File/document-save-as-3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAs.setIcon(icon3)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionPrint = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/File/document-print-5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon4)
        self.actionPrint.setObjectName("actionPrint")
        self.actionClose = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/File/document-close-4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon5)
        self.actionClose.setObjectName("actionClose")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionTips = QtGui.QAction(MainWindow)
        self.actionTips.setObjectName("actionTips")
        self.actionAddSection = QtGui.QAction(MainWindow)
        self.actionAddSection.setObjectName("actionAddSection")
        self.actionRemoveSection = QtGui.QAction(MainWindow)
        self.actionRemoveSection.setObjectName("actionRemoveSection")
        self.actionUpdateSection = QtGui.QAction(MainWindow)
        self.actionUpdateSection.setObjectName("actionUpdateSection")
        self.actionAddComponent = QtGui.QAction(MainWindow)
        self.actionAddComponent.setObjectName("actionAddComponent")
        self.actionRemoveComponent = QtGui.QAction(MainWindow)
        self.actionRemoveComponent.setObjectName("actionRemoveComponent")
        self.actionUpdateComponent = QtGui.QAction(MainWindow)
        self.actionUpdateComponent.setObjectName("actionUpdateComponent")
        self.actionAddStrategy = QtGui.QAction(MainWindow)
        self.actionAddStrategy.setObjectName("actionAddStrategy")
        self.actionRemoveStrategy = QtGui.QAction(MainWindow)
        self.actionRemoveStrategy.setObjectName("actionRemoveStrategy")
        self.actionUpdateStrategy = QtGui.QAction(MainWindow)
        self.actionUpdateStrategy.setObjectName("actionUpdateStrategy")
        self.actionAddSentence = QtGui.QAction(MainWindow)
        self.actionAddSentence.setObjectName("actionAddSentence")
        self.actionRemoveSentence = QtGui.QAction(MainWindow)
        self.actionRemoveSentence.setObjectName("actionRemoveSentence")
        self.actionUpdateSentence = QtGui.QAction(MainWindow)
        self.actionUpdateSentence.setObjectName("actionUpdateSentence")
        self.actionImport = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/File/document-import-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImport.setIcon(icon6)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/File/document-export-4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport.setIcon(icon7)
        self.actionExport.setObjectName("actionExport")
        self.actionTipsSection = QtGui.QAction(MainWindow)
        self.actionTipsSection.setObjectName("actionTipsSection")
        self.actionTipsComponent = QtGui.QAction(MainWindow)
        self.actionTipsComponent.setObjectName("actionTipsComponent")
        self.actionTipsStrategy = QtGui.QAction(MainWindow)
        self.actionTipsStrategy.setObjectName("actionTipsStrategy")
        self.actionTipsSentence = QtGui.QAction(MainWindow)
        self.actionTipsSentence.setObjectName("actionTipsSentence")
        self.actionStripOptions = QtGui.QAction(MainWindow)
        self.actionStripOptions.setObjectName("actionStripOptions")
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionTips)
        self.menuHelp.addAction(self.actionAbout)
        self.menuSection.addSeparator()
        self.menuSection.addAction(self.actionTipsSection)
        self.menuComponent.addSeparator()
        self.menuComponent.addAction(self.actionTipsComponent)
        self.menuStrategy.addSeparator()
        self.menuStrategy.addAction(self.actionTipsStrategy)
        self.menuSentence.addSeparator()
        self.menuSentence.addAction(self.actionTipsSentence)
        self.menuSettings.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSection.menuAction())
        self.menubar.addAction(self.menuComponent.menuAction())
        self.menubar.addAction(self.menuStrategy.menuAction())
        self.menubar.addAction(self.menuSentence.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPrint)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionImport)
        self.toolBar.addAction(self.actionExport)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClose)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButtonClearLog, QtCore.SIGNAL("clicked(bool)"), self.textEditLogView.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Sci Corpus ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSentenceRemove.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.labelReference.setText(QtGui.QApplication.translate("MainWindow", "Reference", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSentenceUpdate.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSentenceAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Sentence", None, QtGui.QApplication.UnicodeUTF8))
        self.textEditSentence.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSection.setTitle(QtGui.QApplication.translate("MainWindow", "Section", None, QtGui.QApplication.UnicodeUTF8))
        self.menuComponent.setTitle(QtGui.QApplication.translate("MainWindow", "Component", None, QtGui.QApplication.UnicodeUTF8))
        self.menuStrategy.setTitle(QtGui.QApplication.translate("MainWindow", "Strategy", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSentence.setTitle(QtGui.QApplication.translate("MainWindow", "Sentence", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetSection.setWindowTitle(QtGui.QApplication.translate("MainWindow", "  Section", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSectionRemove.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSectionAdd.setStatusTip(QtGui.QApplication.translate("MainWindow", "Add a new  section", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSectionAdd.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>This Strategy add a new section when you write it in line edit field and than press add button.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSectionAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSectionUpdate.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Selected:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSelectedSection.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Highlighted:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelHighlightedSection.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Total:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTotalSection.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetComponent.setWindowTitle(QtGui.QApplication.translate("MainWindow", "  Component", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonComponentAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonComponentRemove.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonComponentUpdate.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Selected: ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSelectedComponent.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Highlighted:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelHighlightedComponent.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Total:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTotalComponent.setText(QtGui.QApplication.translate("MainWindow", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetStrategy.setWindowTitle(QtGui.QApplication.translate("MainWindow", "  Strategy", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonStrategyAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonStrategyRemove.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonStrategyUpdate.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Selected: ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSelectedStrategy.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Highlighted:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelHighlightedStrategy.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Total: ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTotalStrategy.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetTableView.setWindowTitle(QtGui.QApplication.translate("MainWindow", "  Table View", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxReference.setText(QtGui.QApplication.translate("MainWindow", "Reference", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxStrip.setText(QtGui.QApplication.translate("MainWindow", "Strip Sentence", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxSection.setText(QtGui.QApplication.translate("MainWindow", "Section", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxStrategy.setText(QtGui.QApplication.translate("MainWindow", "Strategy", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxComponent.setText(QtGui.QApplication.translate("MainWindow", "Component", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxSentence.setText(QtGui.QApplication.translate("MainWindow", "Sentence", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Selected: ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSelectedSentence.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Highlighted:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelHighlightedSentence.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Total:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTotalSentence.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetSentence.setSortingEnabled(True)
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetLogView.setWindowTitle(QtGui.QApplication.translate("MainWindow", "  Log View", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonClearLog.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setText(QtGui.QApplication.translate("MainWindow", "Print to PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTips.setText(QtGui.QApplication.translate("MainWindow", "Tips", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddSection.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveSection.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdateSection.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddComponent.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveComponent.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdateComponent.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddStrategy.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveStrategy.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdateStrategy.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddSentence.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveSentence.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdateSentence.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport.setText(QtGui.QApplication.translate("MainWindow", "Import ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport.setText(QtGui.QApplication.translate("MainWindow", "Export ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTipsSection.setText(QtGui.QApplication.translate("MainWindow", "Tips", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTipsComponent.setText(QtGui.QApplication.translate("MainWindow", "Tips", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTipsStrategy.setText(QtGui.QApplication.translate("MainWindow", "Tips", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTipsSentence.setText(QtGui.QApplication.translate("MainWindow", "Tips", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStripOptions.setText(QtGui.QApplication.translate("MainWindow", "Strip Options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))

from sci_corpus.ui import sci_corpus_resource_rc
