# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Mon Apr 28 15:53:04 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1042, 938)
        font = QtGui.QFont()
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayoutMainWindow = QtGui.QGridLayout()
        self.gridLayoutMainWindow.setObjectName("gridLayoutMainWindow")
        self.textEditSentence = QtGui.QTextEdit(self.centralwidget)
        self.textEditSentence.setMinimumSize(QtCore.QSize(500, 0))
        self.textEditSentence.setMaximumSize(QtCore.QSize(16777215, 120))
        self.textEditSentence.setObjectName("textEditSentence")
        self.gridLayoutMainWindow.addWidget(self.textEditSentence, 1, 3, 2, 5)
        self.tableWidgetSentence = QtGui.QTableWidget(self.centralwidget)
        self.tableWidgetSentence.setAlternatingRowColors(True)
        self.tableWidgetSentence.setObjectName("tableWidgetSentence")
        self.tableWidgetSentence.setColumnCount(1)
        self.tableWidgetSentence.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSentence.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSentence.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSentence.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSentence.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSentence.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSentence.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSentence.setItem(2, 0, item)
        self.tableWidgetSentence.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidgetSentence.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetSentence.verticalHeader().setStretchLastSection(False)
        self.gridLayoutMainWindow.addWidget(self.tableWidgetSentence, 4, 3, 6, 6)
        self.labelSentence = QtGui.QLabel(self.centralwidget)
        self.labelSentence.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.labelSentence.setFont(font)
        self.labelSentence.setObjectName("labelSentence")
        self.gridLayoutMainWindow.addWidget(self.labelSentence, 0, 3, 1, 1)
        self.pushButtonSentenceAdd = QtGui.QPushButton(self.centralwidget)
        self.pushButtonSentenceAdd.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonSentenceAdd.setObjectName("pushButtonSentenceAdd")
        self.gridLayoutMainWindow.addWidget(self.pushButtonSentenceAdd, 0, 5, 1, 1)
        self.pushButtonSentenceUpdate = QtGui.QPushButton(self.centralwidget)
        self.pushButtonSentenceUpdate.setMaximumSize(QtCore.QSize(85, 16777215))
        self.pushButtonSentenceUpdate.setObjectName("pushButtonSentenceUpdate")
        self.gridLayoutMainWindow.addWidget(self.pushButtonSentenceUpdate, 0, 7, 1, 1)
        self.pushButtonSentenceRemove = QtGui.QPushButton(self.centralwidget)
        self.pushButtonSentenceRemove.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonSentenceRemove.setObjectName("pushButtonSentenceRemove")
        self.gridLayoutMainWindow.addWidget(self.pushButtonSentenceRemove, 0, 6, 1, 1)
        self.labelReference = QtGui.QLabel(self.centralwidget)
        self.labelReference.setObjectName("labelReference")
        self.gridLayoutMainWindow.addWidget(self.labelReference, 3, 3, 1, 1)
        self.lineEditReference = QtGui.QLineEdit(self.centralwidget)
        self.lineEditReference.setObjectName("lineEditReference")
        self.gridLayoutMainWindow.addWidget(self.lineEditReference, 3, 4, 1, 4)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(180, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBoxSection = QtGui.QCheckBox(self.groupBox)
        self.checkBoxSection.setObjectName("checkBoxSection")
        self.verticalLayout.addWidget(self.checkBoxSection)
        self.checkBoxSubSection = QtGui.QCheckBox(self.groupBox)
        self.checkBoxSubSection.setObjectName("checkBoxSubSection")
        self.verticalLayout.addWidget(self.checkBoxSubSection)
        self.checkBoxFunction = QtGui.QCheckBox(self.groupBox)
        self.checkBoxFunction.setObjectName("checkBoxFunction")
        self.verticalLayout.addWidget(self.checkBoxFunction)
        self.checkBoxStrip = QtGui.QCheckBox(self.groupBox)
        self.checkBoxStrip.setObjectName("checkBoxStrip")
        self.verticalLayout.addWidget(self.checkBoxStrip)
        self.checkBoxReference = QtGui.QCheckBox(self.groupBox)
        self.checkBoxReference.setObjectName("checkBoxReference")
        self.verticalLayout.addWidget(self.checkBoxReference)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayoutMainWindow.addWidget(self.groupBox, 0, 8, 4, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setStyleSheet("color: rgb(180, 180, 180);")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.labelSelectedSentence = QtGui.QLabel(self.centralwidget)
        self.labelSelectedSentence.setStyleSheet("color: rgb(180, 180, 180);")
        self.labelSelectedSentence.setObjectName("labelSelectedSentence")
        self.horizontalLayout_3.addWidget(self.labelSelectedSentence)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setStyleSheet("color: rgb(180, 180, 180);")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.labelShownSentence = QtGui.QLabel(self.centralwidget)
        self.labelShownSentence.setStyleSheet("color: rgb(180, 180, 180);")
        self.labelShownSentence.setObjectName("labelShownSentence")
        self.horizontalLayout_3.addWidget(self.labelShownSentence)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setStyleSheet("color: rgb(180, 180, 180);")
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.labelTotalSentence = QtGui.QLabel(self.centralwidget)
        self.labelTotalSentence.setStyleSheet("color: rgb(180, 180, 180);")
        self.labelTotalSentence.setObjectName("labelTotalSentence")
        self.horizontalLayout_3.addWidget(self.labelTotalSentence)
        self.gridLayoutMainWindow.addLayout(self.horizontalLayout_3, 0, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayoutMainWindow, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1042, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSection = QtGui.QMenu(self.menubar)
        self.menuSection.setObjectName("menuSection")
        self.menuSubSection = QtGui.QMenu(self.menubar)
        self.menuSubSection.setObjectName("menuSubSection")
        self.menuFunction = QtGui.QMenu(self.menubar)
        self.menuFunction.setObjectName("menuFunction")
        self.menuSentence = QtGui.QMenu(self.menubar)
        self.menuSentence.setObjectName("menuSentence")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidgetSection = QtGui.QDockWidget(MainWindow)
        self.dockWidgetSection.setObjectName("dockWidgetSection")
        self.dockWidgetContentsSection = QtGui.QWidget()
        self.dockWidgetContentsSection.setObjectName("dockWidgetContentsSection")
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContentsSection)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonSectionRemove = QtGui.QPushButton(self.dockWidgetContentsSection)
        self.pushButtonSectionRemove.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonSectionRemove.setObjectName("pushButtonSectionRemove")
        self.gridLayout.addWidget(self.pushButtonSectionRemove, 0, 2, 1, 1)
        self.lineEditSection = QtGui.QLineEdit(self.dockWidgetContentsSection)
        self.lineEditSection.setText("")
        self.lineEditSection.setObjectName("lineEditSection")
        self.gridLayout.addWidget(self.lineEditSection, 0, 0, 1, 1)
        self.pushButtonSectionAdd = QtGui.QPushButton(self.dockWidgetContentsSection)
        self.pushButtonSectionAdd.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonSectionAdd.setObjectName("pushButtonSectionAdd")
        self.gridLayout.addWidget(self.pushButtonSectionAdd, 0, 1, 1, 1)
        self.pushButtonSectionUpdate = QtGui.QPushButton(self.dockWidgetContentsSection)
        self.pushButtonSectionUpdate.setObjectName("pushButtonSectionUpdate")
        self.gridLayout.addWidget(self.pushButtonSectionUpdate, 0, 3, 1, 1)
        self.listWidgetSection = QtGui.QListWidget(self.dockWidgetContentsSection)
        self.listWidgetSection.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidgetSection.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.listWidgetSection.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.listWidgetSection.setAlternatingRowColors(False)
        self.listWidgetSection.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidgetSection.setMovement(QtGui.QListView.Free)
        self.listWidgetSection.setModelColumn(0)
        self.listWidgetSection.setUniformItemSizes(False)
        self.listWidgetSection.setSelectionRectVisible(True)
        self.listWidgetSection.setObjectName("listWidgetSection")
        QtGui.QListWidgetItem(self.listWidgetSection)
        QtGui.QListWidgetItem(self.listWidgetSection)
        QtGui.QListWidgetItem(self.listWidgetSection)
        QtGui.QListWidgetItem(self.listWidgetSection)
        QtGui.QListWidgetItem(self.listWidgetSection)
        QtGui.QListWidgetItem(self.listWidgetSection)
        self.gridLayout.addWidget(self.listWidgetSection, 1, 0, 1, 4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.dockWidgetContentsSection)
        self.label.setStyleSheet("color: rgb(180, 180, 180);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.labelSelectedSection = QtGui.QLabel(self.dockWidgetContentsSection)
        self.labelSelectedSection.setStyleSheet("color: rgb(180, 180, 180);")
        self.labelSelectedSection.setObjectName("labelSelectedSection")
        self.horizontalLayout.addWidget(self.labelSelectedSection)
        self.label_3 = QtGui.QLabel(self.dockWidgetContentsSection)
        self.label_3.setStyleSheet("color: rgb(180, 180, 180);")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.labelShownSection = QtGui.QLabel(self.dockWidgetContentsSection)
        self.labelShownSection.setStyleSheet("color: rgb(180, 180, 180);")
        self.labelShownSection.setObjectName("labelShownSection")
        self.horizontalLayout.addWidget(self.labelShownSection)
        self.label_2 = QtGui.QLabel(self.dockWidgetContentsSection)
        self.label_2.setStyleSheet("color: rgb(180, 180, 180);")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.labelTotalSection = QtGui.QLabel(self.dockWidgetContentsSection)
        self.labelTotalSection.setStyleSheet("color: rgb(180, 180, 180);")
        self.labelTotalSection.setObjectName("labelTotalSection")
        self.horizontalLayout.addWidget(self.labelTotalSection)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 3, 4)
        self.dockWidgetSection.setWidget(self.dockWidgetContentsSection)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidgetSection)
        self.dockWidgetSubSection = QtGui.QDockWidget(MainWindow)
        self.dockWidgetSubSection.setObjectName("dockWidgetSubSection")
        self.dockWidgetContentsSubSection = QtGui.QWidget()
        self.dockWidgetContentsSubSection.setObjectName("dockWidgetContentsSubSection")
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContentsSubSection)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEditSubSection = QtGui.QLineEdit(self.dockWidgetContentsSubSection)
        self.lineEditSubSection.setObjectName("lineEditSubSection")
        self.gridLayout_3.addWidget(self.lineEditSubSection, 0, 0, 1, 1)
        self.pushButtonSubSectionAdd = QtGui.QPushButton(self.dockWidgetContentsSubSection)
        self.pushButtonSubSectionAdd.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonSubSectionAdd.setObjectName("pushButtonSubSectionAdd")
        self.gridLayout_3.addWidget(self.pushButtonSubSectionAdd, 0, 1, 1, 1)
        self.pushButtonSubSectionRemove = QtGui.QPushButton(self.dockWidgetContentsSubSection)
        self.pushButtonSubSectionRemove.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonSubSectionRemove.setObjectName("pushButtonSubSectionRemove")
        self.gridLayout_3.addWidget(self.pushButtonSubSectionRemove, 0, 2, 1, 1)
        self.pushButtonSubSectionUpdate = QtGui.QPushButton(self.dockWidgetContentsSubSection)
        self.pushButtonSubSectionUpdate.setObjectName("pushButtonSubSectionUpdate")
        self.gridLayout_3.addWidget(self.pushButtonSubSectionUpdate, 0, 3, 1, 1)
        self.listWidgetSubSection = QtGui.QListWidget(self.dockWidgetContentsSubSection)
        self.listWidgetSubSection.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidgetSubSection.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.listWidgetSubSection.setAlternatingRowColors(False)
        self.listWidgetSubSection.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidgetSubSection.setMovement(QtGui.QListView.Free)
        self.listWidgetSubSection.setSelectionRectVisible(True)
        self.listWidgetSubSection.setObjectName("listWidgetSubSection")
        QtGui.QListWidgetItem(self.listWidgetSubSection)
        QtGui.QListWidgetItem(self.listWidgetSubSection)
        QtGui.QListWidgetItem(self.listWidgetSubSection)
        QtGui.QListWidgetItem(self.listWidgetSubSection)
        QtGui.QListWidgetItem(self.listWidgetSubSection)
        QtGui.QListWidgetItem(self.listWidgetSubSection)
        self.gridLayout_3.addWidget(self.listWidgetSubSection, 1, 0, 1, 4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtGui.QLabel(self.dockWidgetContentsSubSection)
        self.label_7.setStyleSheet("color: rgb(180, 180, 180);")
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.labelSelectedSubSection = QtGui.QLabel(self.dockWidgetContentsSubSection)
        self.labelSelectedSubSection.setStyleSheet("color: rgb(180, 180, 180);")
        self.labelSelectedSubSection.setObjectName("labelSelectedSubSection")
        self.horizontalLayout_2.addWidget(self.labelSelectedSubSection)
        self.label_9 = QtGui.QLabel(self.dockWidgetContentsSubSection)
        self.label_9.setStyleSheet("color: rgb(180, 180, 180);")
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.labelShownSubSection = QtGui.QLabel(self.dockWidgetContentsSubSection)
        self.labelShownSubSection.setStyleSheet("color: rgb(180, 180, 180);")
        self.labelShownSubSection.setObjectName("labelShownSubSection")
        self.horizontalLayout_2.addWidget(self.labelShownSubSection)
        self.label_8 = QtGui.QLabel(self.dockWidgetContentsSubSection)
        self.label_8.setStyleSheet("color: rgb(180, 180, 180);")
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.labelTotalSubSection = QtGui.QLabel(self.dockWidgetContentsSubSection)
        self.labelTotalSubSection.setStyleSheet("color: rgb(180, 180, 180);")
        self.labelTotalSubSection.setObjectName("labelTotalSubSection")
        self.horizontalLayout_2.addWidget(self.labelTotalSubSection)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 2, 4)
        self.dockWidgetSubSection.setWidget(self.dockWidgetContentsSubSection)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidgetSubSection)
        self.dockWidgetFunction = QtGui.QDockWidget(MainWindow)
        self.dockWidgetFunction.setObjectName("dockWidgetFunction")
        self.dockWidgetContentsFunction = QtGui.QWidget()
        self.dockWidgetContentsFunction.setObjectName("dockWidgetContentsFunction")
        self.gridLayout_4 = QtGui.QGridLayout(self.dockWidgetContentsFunction)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEditFunction = QtGui.QLineEdit(self.dockWidgetContentsFunction)
        self.lineEditFunction.setObjectName("lineEditFunction")
        self.gridLayout_4.addWidget(self.lineEditFunction, 0, 0, 1, 1)
        self.pushButtonFunctionAdd = QtGui.QPushButton(self.dockWidgetContentsFunction)
        self.pushButtonFunctionAdd.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonFunctionAdd.setObjectName("pushButtonFunctionAdd")
        self.gridLayout_4.addWidget(self.pushButtonFunctionAdd, 0, 1, 1, 1)
        self.pushButtonFunctionRemove = QtGui.QPushButton(self.dockWidgetContentsFunction)
        self.pushButtonFunctionRemove.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonFunctionRemove.setObjectName("pushButtonFunctionRemove")
        self.gridLayout_4.addWidget(self.pushButtonFunctionRemove, 0, 2, 1, 1)
        self.pushButtonFunctionUpdate = QtGui.QPushButton(self.dockWidgetContentsFunction)
        self.pushButtonFunctionUpdate.setObjectName("pushButtonFunctionUpdate")
        self.gridLayout_4.addWidget(self.pushButtonFunctionUpdate, 0, 3, 1, 1)
        self.listWidgetFunction = QtGui.QListWidget(self.dockWidgetContentsFunction)
        self.listWidgetFunction.setMidLineWidth(0)
        self.listWidgetFunction.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.listWidgetFunction.setAlternatingRowColors(False)
        self.listWidgetFunction.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidgetFunction.setMovement(QtGui.QListView.Free)
        self.listWidgetFunction.setSelectionRectVisible(True)
        self.listWidgetFunction.setObjectName("listWidgetFunction")
        QtGui.QListWidgetItem(self.listWidgetFunction)
        QtGui.QListWidgetItem(self.listWidgetFunction)
        self.gridLayout_4.addWidget(self.listWidgetFunction, 1, 0, 1, 4)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_14 = QtGui.QLabel(self.dockWidgetContentsFunction)
        self.label_14.setStyleSheet("color: rgb(180, 180, 180);")
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_4.addWidget(self.label_14)
        self.labelSelectedFunction = QtGui.QLabel(self.dockWidgetContentsFunction)
        self.labelSelectedFunction.setStyleSheet("color: rgb(180, 180, 180);")
        self.labelSelectedFunction.setObjectName("labelSelectedFunction")
        self.horizontalLayout_4.addWidget(self.labelSelectedFunction)
        self.label_15 = QtGui.QLabel(self.dockWidgetContentsFunction)
        self.label_15.setStyleSheet("color: rgb(180, 180, 180);")
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        self.labelShownFunction = QtGui.QLabel(self.dockWidgetContentsFunction)
        self.labelShownFunction.setStyleSheet("color: rgb(180, 180, 180);")
        self.labelShownFunction.setObjectName("labelShownFunction")
        self.horizontalLayout_4.addWidget(self.labelShownFunction)
        self.label_17 = QtGui.QLabel(self.dockWidgetContentsFunction)
        self.label_17.setStyleSheet("color: rgb(180, 180, 180);")
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.labelTotalFunction = QtGui.QLabel(self.dockWidgetContentsFunction)
        self.labelTotalFunction.setStyleSheet("color: rgb(180, 180, 180);")
        self.labelTotalFunction.setObjectName("labelTotalFunction")
        self.horizontalLayout_4.addWidget(self.labelTotalFunction)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 2, 0, 1, 4)
        self.dockWidgetFunction.setWidget(self.dockWidgetContentsFunction)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidgetFunction)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtGui.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionPrint = QtGui.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionTips = QtGui.QAction(MainWindow)
        self.actionTips.setObjectName("actionTips")
        self.actionAddSection = QtGui.QAction(MainWindow)
        self.actionAddSection.setObjectName("actionAddSection")
        self.actionRemoveSection = QtGui.QAction(MainWindow)
        self.actionRemoveSection.setObjectName("actionRemoveSection")
        self.actionUpdateSection = QtGui.QAction(MainWindow)
        self.actionUpdateSection.setObjectName("actionUpdateSection")
        self.actionAddSubSection = QtGui.QAction(MainWindow)
        self.actionAddSubSection.setObjectName("actionAddSubSection")
        self.actionRemoveSubSection = QtGui.QAction(MainWindow)
        self.actionRemoveSubSection.setObjectName("actionRemoveSubSection")
        self.actionUpdateSubSection = QtGui.QAction(MainWindow)
        self.actionUpdateSubSection.setObjectName("actionUpdateSubSection")
        self.actionAddFunction = QtGui.QAction(MainWindow)
        self.actionAddFunction.setObjectName("actionAddFunction")
        self.actionRemoveFunction = QtGui.QAction(MainWindow)
        self.actionRemoveFunction.setObjectName("actionRemoveFunction")
        self.actionUpdateFunction = QtGui.QAction(MainWindow)
        self.actionUpdateFunction.setObjectName("actionUpdateFunction")
        self.actionAddSentence = QtGui.QAction(MainWindow)
        self.actionAddSentence.setObjectName("actionAddSentence")
        self.actionRemoveSentence = QtGui.QAction(MainWindow)
        self.actionRemoveSentence.setObjectName("actionRemoveSentence")
        self.actionUpdateSentence = QtGui.QAction(MainWindow)
        self.actionUpdateSentence.setObjectName("actionUpdateSentence")
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExportXML = QtGui.QAction(MainWindow)
        self.actionExportXML.setObjectName("actionExportXML")
        self.actionImportJSON = QtGui.QAction(MainWindow)
        self.actionImportJSON.setObjectName("actionImportJSON")
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionTipsSection = QtGui.QAction(MainWindow)
        self.actionTipsSection.setObjectName("actionTipsSection")
        self.actionTipsSubSection = QtGui.QAction(MainWindow)
        self.actionTipsSubSection.setObjectName("actionTipsSubSection")
        self.actionTipsFunction = QtGui.QAction(MainWindow)
        self.actionTipsFunction.setObjectName("actionTipsFunction")
        self.actionTipsSentence = QtGui.QAction(MainWindow)
        self.actionTipsSentence.setObjectName("actionTipsSentence")
        self.actionStripOptions = QtGui.QAction(MainWindow)
        self.actionStripOptions.setObjectName("actionStripOptions")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionTips)
        self.menuHelp.addAction(self.actionAbout)
        self.menuSection.addAction(self.actionAddSection)
        self.menuSection.addAction(self.actionRemoveSection)
        self.menuSection.addAction(self.actionUpdateSection)
        self.menuSection.addSeparator()
        self.menuSection.addAction(self.actionTipsSection)
        self.menuSubSection.addAction(self.actionAddSubSection)
        self.menuSubSection.addAction(self.actionRemoveSubSection)
        self.menuSubSection.addAction(self.actionUpdateSubSection)
        self.menuSubSection.addSeparator()
        self.menuSubSection.addAction(self.actionTipsSubSection)
        self.menuFunction.addAction(self.actionAddFunction)
        self.menuFunction.addAction(self.actionRemoveFunction)
        self.menuFunction.addAction(self.actionUpdateFunction)
        self.menuFunction.addSeparator()
        self.menuFunction.addAction(self.actionTipsFunction)
        self.menuSentence.addAction(self.actionAddSentence)
        self.menuSentence.addAction(self.actionRemoveSentence)
        self.menuSentence.addAction(self.actionUpdateSentence)
        self.menuSentence.addSeparator()
        self.menuSentence.addAction(self.actionStripOptions)
        self.menuSentence.addSeparator()
        self.menuSentence.addAction(self.actionTipsSentence)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSection.menuAction())
        self.menubar.addAction(self.menuSubSection.menuAction())
        self.menubar.addAction(self.menuFunction.menuAction())
        self.menubar.addAction(self.menuSentence.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Sci Corpus ", None, QtGui.QApplication.UnicodeUTF8))
        self.textEditSentence.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Type here your sentence and press enter to add. Specific parts of the sentence can be smart ommited by using {{ }}, see an example:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Nowadays it is dangerous {{to shit}} in the forest.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In a future version we will able to show like this: </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Nowadays it is dangerous ... in the forest.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetSentence.setSortingEnabled(True)
        self.tableWidgetSentence.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetSentence.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetSentence.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetSentence.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Sentence", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidgetSentence.isSortingEnabled()
        self.tableWidgetSentence.setSortingEnabled(False)
        self.tableWidgetSentence.item(0, 0).setText(QtGui.QApplication.translate("MainWindow", "a teste", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetSentence.item(1, 0).setText(QtGui.QApplication.translate("MainWindow", "b teste", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetSentence.item(2, 0).setText(QtGui.QApplication.translate("MainWindow", "c teste", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetSentence.setSortingEnabled(__sortingEnabled)
        self.labelSentence.setText(QtGui.QApplication.translate("MainWindow", "Sentece", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSentenceAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSentenceUpdate.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSentenceRemove.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.labelReference.setText(QtGui.QApplication.translate("MainWindow", "Reference", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Table View", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxSection.setText(QtGui.QApplication.translate("MainWindow", "Section", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxSubSection.setText(QtGui.QApplication.translate("MainWindow", "Sub Section", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxFunction.setText(QtGui.QApplication.translate("MainWindow", "Function", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxStrip.setText(QtGui.QApplication.translate("MainWindow", "Strip Sentence", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxReference.setText(QtGui.QApplication.translate("MainWindow", "Reference", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Selected: ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSelectedSentence.setText(QtGui.QApplication.translate("MainWindow", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Shown: ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelShownSentence.setText(QtGui.QApplication.translate("MainWindow", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Total:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTotalSentence.setText(QtGui.QApplication.translate("MainWindow", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSection.setTitle(QtGui.QApplication.translate("MainWindow", "Section", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSubSection.setTitle(QtGui.QApplication.translate("MainWindow", "Sub Section", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFunction.setTitle(QtGui.QApplication.translate("MainWindow", "Function", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSentence.setTitle(QtGui.QApplication.translate("MainWindow", "Sentence", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetSection.setWindowTitle(QtGui.QApplication.translate("MainWindow", "  Section", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSectionRemove.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSectionAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSectionUpdate.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listWidgetSection.isSortingEnabled()
        self.listWidgetSection.setSortingEnabled(False)
        self.listWidgetSection.item(0).setText(QtGui.QApplication.translate("MainWindow", "Abstract", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidgetSection.item(1).setText(QtGui.QApplication.translate("MainWindow", "Introduction", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidgetSection.item(2).setText(QtGui.QApplication.translate("MainWindow", "Methodology", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidgetSection.item(3).setText(QtGui.QApplication.translate("MainWindow", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidgetSection.item(4).setText(QtGui.QApplication.translate("MainWindow", "Discussion", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidgetSection.item(5).setText(QtGui.QApplication.translate("MainWindow", "Conclusion", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidgetSection.setSortingEnabled(__sortingEnabled)
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Selected:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSelectedSection.setText(QtGui.QApplication.translate("MainWindow", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Shown: ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelShownSection.setText(QtGui.QApplication.translate("MainWindow", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Total:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTotalSection.setText(QtGui.QApplication.translate("MainWindow", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetSubSection.setWindowTitle(QtGui.QApplication.translate("MainWindow", "  Sub Section", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSubSectionAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSubSectionRemove.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSubSectionUpdate.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listWidgetSubSection.isSortingEnabled()
        self.listWidgetSubSection.setSortingEnabled(False)
        self.listWidgetSubSection.item(0).setText(QtGui.QApplication.translate("MainWindow", "Context", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidgetSubSection.item(1).setText(QtGui.QApplication.translate("MainWindow", "Gap", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidgetSubSection.item(2).setText(QtGui.QApplication.translate("MainWindow", "Propose", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidgetSubSection.item(3).setText(QtGui.QApplication.translate("MainWindow", "Methodology", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidgetSubSection.item(4).setText(QtGui.QApplication.translate("MainWindow", "Result", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidgetSubSection.item(5).setText(QtGui.QApplication.translate("MainWindow", "Conclusion", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidgetSubSection.setSortingEnabled(__sortingEnabled)
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Selected: ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSelectedSubSection.setText(QtGui.QApplication.translate("MainWindow", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Shown:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelShownSubSection.setText(QtGui.QApplication.translate("MainWindow", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Total:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTotalSubSection.setText(QtGui.QApplication.translate("MainWindow", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetFunction.setWindowTitle(QtGui.QApplication.translate("MainWindow", "  Function", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonFunctionAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonFunctionRemove.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonFunctionUpdate.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listWidgetFunction.isSortingEnabled()
        self.listWidgetFunction.setSortingEnabled(False)
        self.listWidgetFunction.item(0).setText(QtGui.QApplication.translate("MainWindow", "Cite previous research", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidgetFunction.item(1).setText(QtGui.QApplication.translate("MainWindow", "Present a hipotesys", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidgetFunction.setSortingEnabled(__sortingEnabled)
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Selected: ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSelectedFunction.setText(QtGui.QApplication.translate("MainWindow", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Shown: ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelShownFunction.setText(QtGui.QApplication.translate("MainWindow", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Total: ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTotalFunction.setText(QtGui.QApplication.translate("MainWindow", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setText(QtGui.QApplication.translate("MainWindow", "Print", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTips.setText(QtGui.QApplication.translate("MainWindow", "Tips", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddSection.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveSection.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdateSection.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddSubSection.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveSubSection.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdateSubSection.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddFunction.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveFunction.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdateFunction.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddSentence.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveSentence.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdateSentence.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport.setText(QtGui.QApplication.translate("MainWindow", "Import ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportXML.setText(QtGui.QApplication.translate("MainWindow", "Export XML", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportJSON.setText(QtGui.QApplication.translate("MainWindow", "Import JSON", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport.setText(QtGui.QApplication.translate("MainWindow", "Export ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTipsSection.setText(QtGui.QApplication.translate("MainWindow", "Tips", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTipsSubSection.setText(QtGui.QApplication.translate("MainWindow", "Tips", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTipsFunction.setText(QtGui.QApplication.translate("MainWindow", "Tips", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTipsSentence.setText(QtGui.QApplication.translate("MainWindow", "Tips", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStripOptions.setText(QtGui.QApplication.translate("MainWindow", "Strip Options", None, QtGui.QApplication.UnicodeUTF8))

