# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pdf_dlg.ui'
#
# Created: Wed May 28 16:05:28 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(911, 334)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonCancel = QtGui.QPushButton(Dialog)
        self.pushButtonCancel.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.pushButtonOk = QtGui.QPushButton(Dialog)
        self.pushButtonOk.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.horizontalLayout.addWidget(self.pushButtonOk)
        self.gridLayout.addLayout(self.horizontalLayout, 9, 0, 1, 4)
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtGui.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditTitle = QtGui.QLineEdit(Dialog)
        self.lineEditTitle.setObjectName("lineEditTitle")
        self.gridLayout.addWidget(self.lineEditTitle, 0, 1, 1, 3)
        self.lineEditAuthor = QtGui.QLineEdit(Dialog)
        self.lineEditAuthor.setObjectName("lineEditAuthor")
        self.gridLayout.addWidget(self.lineEditAuthor, 1, 1, 1, 3)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.textEditDescription = QtGui.QTextEdit(Dialog)
        self.textEditDescription.setObjectName("textEditDescription")
        self.gridLayout.addWidget(self.textEditDescription, 2, 1, 1, 3)
        self.lineEditPath = QtGui.QLineEdit(Dialog)
        self.lineEditPath.setObjectName("lineEditPath")
        self.gridLayout.addWidget(self.lineEditPath, 3, 1, 1, 2)
        self.pushButtonPath = QtGui.QPushButton(Dialog)
        self.pushButtonPath.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonPath.setObjectName("pushButtonPath")
        self.gridLayout.addWidget(self.pushButtonPath, 3, 3, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBoxMargins = QtGui.QGroupBox(Dialog)
        self.groupBoxMargins.setObjectName("groupBoxMargins")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxMargins)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.doubleSpinBoxTop = QtGui.QDoubleSpinBox(self.groupBoxMargins)
        self.doubleSpinBoxTop.setDecimals(1)
        self.doubleSpinBoxTop.setMaximum(50.0)
        self.doubleSpinBoxTop.setSingleStep(0.1)
        self.doubleSpinBoxTop.setProperty("value", 30.0)
        self.doubleSpinBoxTop.setObjectName("doubleSpinBoxTop")
        self.gridLayout_3.addWidget(self.doubleSpinBoxTop, 0, 1, 1, 1)
        self.doubleSpinBoxBottom = QtGui.QDoubleSpinBox(self.groupBoxMargins)
        self.doubleSpinBoxBottom.setDecimals(1)
        self.doubleSpinBoxBottom.setMaximum(50.0)
        self.doubleSpinBoxBottom.setSingleStep(0.1)
        self.doubleSpinBoxBottom.setProperty("value", 20.0)
        self.doubleSpinBoxBottom.setObjectName("doubleSpinBoxBottom")
        self.gridLayout_3.addWidget(self.doubleSpinBoxBottom, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBoxMargins)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBoxMargins)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBoxMargins)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBoxMargins)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 2, 1, 1)
        self.doubleSpinBoxLeft = QtGui.QDoubleSpinBox(self.groupBoxMargins)
        self.doubleSpinBoxLeft.setDecimals(1)
        self.doubleSpinBoxLeft.setMaximum(50.0)
        self.doubleSpinBoxLeft.setSingleStep(0.1)
        self.doubleSpinBoxLeft.setProperty("value", 30.0)
        self.doubleSpinBoxLeft.setObjectName("doubleSpinBoxLeft")
        self.gridLayout_3.addWidget(self.doubleSpinBoxLeft, 0, 3, 1, 1)
        self.doubleSpinBoxRight = QtGui.QDoubleSpinBox(self.groupBoxMargins)
        self.doubleSpinBoxRight.setDecimals(1)
        self.doubleSpinBoxRight.setMaximum(50.0)
        self.doubleSpinBoxRight.setSingleStep(0.1)
        self.doubleSpinBoxRight.setProperty("value", 20.0)
        self.doubleSpinBoxRight.setObjectName("doubleSpinBoxRight")
        self.gridLayout_3.addWidget(self.doubleSpinBoxRight, 1, 3, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBoxMargins)
        self.groupBoxText = QtGui.QGroupBox(Dialog)
        self.groupBoxText.setObjectName("groupBoxText")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBoxText)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_9 = QtGui.QLabel(self.groupBoxText)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 1, 0, 1, 1)
        self.comboBoxFont = QtGui.QFontComboBox(self.groupBoxText)
        self.comboBoxFont.setMaximumSize(QtCore.QSize(150, 16777215))
        self.comboBoxFont.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBoxFont.setObjectName("comboBoxFont")
        self.gridLayout_5.addWidget(self.comboBoxFont, 0, 1, 1, 1)
        self.spinBoxSize = QtGui.QSpinBox(self.groupBoxText)
        self.spinBoxSize.setObjectName("spinBoxSize")
        self.gridLayout_5.addWidget(self.spinBoxSize, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBoxText)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBoxText)
        self.groupBoxSentence = QtGui.QGroupBox(Dialog)
        self.groupBoxSentence.setObjectName("groupBoxSentence")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBoxSentence)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.radioButtonReplace = QtGui.QRadioButton(self.groupBoxSentence)
        self.radioButtonReplace.setObjectName("radioButtonReplace")
        self.gridLayout_6.addWidget(self.radioButtonReplace, 0, 0, 1, 1)
        self.radioButtonDim = QtGui.QRadioButton(self.groupBoxSentence)
        self.radioButtonDim.setObjectName("radioButtonDim")
        self.gridLayout_6.addWidget(self.radioButtonDim, 1, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBoxSentence)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 1, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Print to PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancel.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOk.setText(QtGui.QApplication.translate("Dialog", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "File name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Author:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Title:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPath.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxMargins.setTitle(QtGui.QApplication.translate("Dialog", "Margins", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxTop.setSuffix(QtGui.QApplication.translate("Dialog", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxBottom.setSuffix(QtGui.QApplication.translate("Dialog", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Top:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Left:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Bottom:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Right:", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxLeft.setSuffix(QtGui.QApplication.translate("Dialog", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxRight.setSuffix(QtGui.QApplication.translate("Dialog", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxText.setTitle(QtGui.QApplication.translate("Dialog", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxSize.setSuffix(QtGui.QApplication.translate("Dialog", "pt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Font:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxSentence.setTitle(QtGui.QApplication.translate("Dialog", "Sentence", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonReplace.setText(QtGui.QApplication.translate("Dialog", "Replace marked/unmarked text", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonDim.setText(QtGui.QApplication.translate("Dialog", "Dim marked/unmarked text", None, QtGui.QApplication.UnicodeUTF8))

