# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sentence_mw.ui'
#
# Created: Wed Jul 16 11:47:00 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindowSentence(object):
    def setupUi(self, MainWindowSentence):
        MainWindowSentence.setObjectName("MainWindowSentence")
        MainWindowSentence.resize(800, 209)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindowSentence.sizePolicy().hasHeightForWidth())
        MainWindowSentence.setSizePolicy(sizePolicy)
        MainWindowSentence.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MainWindowSentence)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonSentenceRemove = QtGui.QPushButton(self.widget)
        self.pushButtonSentenceRemove.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonSentenceRemove.setObjectName("pushButtonSentenceRemove")
        self.gridLayout_2.addWidget(self.pushButtonSentenceRemove, 3, 5, 1, 1)
        self.pushButtonSentenceAdd = QtGui.QPushButton(self.widget)
        self.pushButtonSentenceAdd.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonSentenceAdd.setObjectName("pushButtonSentenceAdd")
        self.gridLayout_2.addWidget(self.pushButtonSentenceAdd, 3, 4, 1, 1)
        self.pushButtonSentenceUpdate = QtGui.QPushButton(self.widget)
        self.pushButtonSentenceUpdate.setMaximumSize(QtCore.QSize(85, 16777215))
        self.pushButtonSentenceUpdate.setObjectName("pushButtonSentenceUpdate")
        self.gridLayout_2.addWidget(self.pushButtonSentenceUpdate, 3, 6, 1, 1)
        self.labelReference = QtGui.QLabel(self.widget)
        self.labelReference.setObjectName("labelReference")
        self.gridLayout_2.addWidget(self.labelReference, 3, 0, 1, 1)
        self.checkBoxAutoClearSentence = QtGui.QCheckBox(self.widget)
        self.checkBoxAutoClearSentence.setObjectName("checkBoxAutoClearSentence")
        self.gridLayout_2.addWidget(self.checkBoxAutoClearSentence, 3, 3, 1, 1)
        self.textEditSentence = QtGui.QTextEdit(self.widget)
        self.textEditSentence.setMinimumSize(QtCore.QSize(0, 0))
        self.textEditSentence.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textEditSentence.setAcceptRichText(False)
        self.textEditSentence.setObjectName("textEditSentence")
        self.gridLayout_2.addWidget(self.textEditSentence, 0, 0, 1, 7)
        self.checkBoxAutoClearReference = QtGui.QCheckBox(self.widget)
        self.checkBoxAutoClearReference.setObjectName("checkBoxAutoClearReference")
        self.gridLayout_2.addWidget(self.checkBoxAutoClearReference, 3, 2, 1, 1)
        self.lineEditReference = QtGui.QLineEdit(self.widget)
        self.lineEditReference.setObjectName("lineEditReference")
        self.gridLayout_2.addWidget(self.lineEditReference, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        MainWindowSentence.setCentralWidget(self.centralwidget)
        self.toolBarEdit = QtGui.QToolBar(MainWindowSentence)
        self.toolBarEdit.setObjectName("toolBarEdit")
        MainWindowSentence.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarEdit)
        self.toolBarView = QtGui.QToolBar(MainWindowSentence)
        self.toolBarView.setObjectName("toolBarView")
        MainWindowSentence.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarView)
        self.actionMark = QtGui.QAction(MainWindowSentence)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Edit/draw-brush.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMark.setIcon(icon)
        self.actionMark.setObjectName("actionMark")
        self.actionCopy = QtGui.QAction(MainWindowSentence)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Edit/edit-copy-8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon1)
        self.actionCopy.setObjectName("actionCopy")
        self.actionRedo = QtGui.QAction(MainWindowSentence)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Edit/edit-redo-8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon2)
        self.actionRedo.setObjectName("actionRedo")
        self.actionUndo = QtGui.QAction(MainWindowSentence)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Edit/edit-undo-8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon3)
        self.actionUndo.setObjectName("actionUndo")
        self.actionSelect_All = QtGui.QAction(MainWindowSentence)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Edit/edit-select-all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelect_All.setIcon(icon4)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionPaste = QtGui.QAction(MainWindowSentence)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Edit/edit-paste-8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon5)
        self.actionPaste.setObjectName("actionPaste")
        self.actionCut = QtGui.QAction(MainWindowSentence)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Edit/edit-cut-8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon6)
        self.actionCut.setObjectName("actionCut")
        self.actionClear = QtGui.QAction(MainWindowSentence)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Edit/edit-clear-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear.setIcon(icon7)
        self.actionClear.setObjectName("actionClear")
        self.actionZoom_In = QtGui.QAction(MainWindowSentence)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/View/zoom-in-3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_In.setIcon(icon8)
        self.actionZoom_In.setObjectName("actionZoom_In")
        self.actionZoom_Out = QtGui.QAction(MainWindowSentence)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/View/zoom-out-3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_Out.setIcon(icon9)
        self.actionZoom_Out.setObjectName("actionZoom_Out")
        self.actionAddSentence = QtGui.QAction(MainWindowSentence)
        self.actionAddSentence.setObjectName("actionAddSentence")
        self.actionRemoveSentence = QtGui.QAction(MainWindowSentence)
        self.actionRemoveSentence.setObjectName("actionRemoveSentence")
        self.actionUpdateSentence = QtGui.QAction(MainWindowSentence)
        self.actionUpdateSentence.setObjectName("actionUpdateSentence")
        self.toolBarEdit.addAction(self.actionMark)
        self.toolBarEdit.addSeparator()
        self.toolBarEdit.addAction(self.actionRedo)
        self.toolBarEdit.addAction(self.actionUndo)
        self.toolBarEdit.addSeparator()
        self.toolBarEdit.addAction(self.actionCut)
        self.toolBarEdit.addAction(self.actionCopy)
        self.toolBarEdit.addAction(self.actionPaste)
        self.toolBarEdit.addSeparator()
        self.toolBarEdit.addAction(self.actionSelect_All)
        self.toolBarEdit.addAction(self.actionClear)
        self.toolBarView.addAction(self.actionZoom_In)
        self.toolBarView.addAction(self.actionZoom_Out)

        self.retranslateUi(MainWindowSentence)
        QtCore.QMetaObject.connectSlotsByName(MainWindowSentence)

    def retranslateUi(self, MainWindowSentence):
        MainWindowSentence.setWindowTitle(QtGui.QApplication.translate("MainWindowSentence", "Sentence Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSentenceRemove.setText(QtGui.QApplication.translate("MainWindowSentence", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSentenceAdd.setText(QtGui.QApplication.translate("MainWindowSentence", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSentenceUpdate.setText(QtGui.QApplication.translate("MainWindowSentence", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.labelReference.setText(QtGui.QApplication.translate("MainWindowSentence", "Reference", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxAutoClearSentence.setText(QtGui.QApplication.translate("MainWindowSentence", "Auto clear sentence", None, QtGui.QApplication.UnicodeUTF8))
        self.textEditSentence.setHtml(QtGui.QApplication.translate("MainWindowSentence", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Type your sentece here.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxAutoClearReference.setText(QtGui.QApplication.translate("MainWindowSentence", "Auto clear reference", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarEdit.setWindowTitle(QtGui.QApplication.translate("MainWindowSentence", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarView.setWindowTitle(QtGui.QApplication.translate("MainWindowSentence", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMark.setText(QtGui.QApplication.translate("MainWindowSentence", "Mark", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMark.setToolTip(QtGui.QApplication.translate("MainWindowSentence", "Mark selected sentence with markers", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMark.setShortcut(QtGui.QApplication.translate("MainWindowSentence", "Ctrl+M", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("MainWindowSentence", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setToolTip(QtGui.QApplication.translate("MainWindowSentence", "Copy selected content", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setShortcut(QtGui.QApplication.translate("MainWindowSentence", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setText(QtGui.QApplication.translate("MainWindowSentence", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setToolTip(QtGui.QApplication.translate("MainWindowSentence", "Redo action", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setShortcut(QtGui.QApplication.translate("MainWindowSentence", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setText(QtGui.QApplication.translate("MainWindowSentence", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setToolTip(QtGui.QApplication.translate("MainWindowSentence", "Undo action", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setShortcut(QtGui.QApplication.translate("MainWindowSentence", "Ctrl+U", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_All.setText(QtGui.QApplication.translate("MainWindowSentence", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_All.setToolTip(QtGui.QApplication.translate("MainWindowSentence", "Select all contents", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_All.setShortcut(QtGui.QApplication.translate("MainWindowSentence", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("MainWindowSentence", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setToolTip(QtGui.QApplication.translate("MainWindowSentence", "Paste content", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setShortcut(QtGui.QApplication.translate("MainWindowSentence", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("MainWindowSentence", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setToolTip(QtGui.QApplication.translate("MainWindowSentence", "Cut content", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setShortcut(QtGui.QApplication.translate("MainWindowSentence", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear.setText(QtGui.QApplication.translate("MainWindowSentence", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear.setToolTip(QtGui.QApplication.translate("MainWindowSentence", "Clear content", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_In.setText(QtGui.QApplication.translate("MainWindowSentence", "Zoom In", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_In.setToolTip(QtGui.QApplication.translate("MainWindowSentence", "Zoom In", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_In.setShortcut(QtGui.QApplication.translate("MainWindowSentence", "Ctrl+=", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_Out.setText(QtGui.QApplication.translate("MainWindowSentence", "Zoom Out", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_Out.setToolTip(QtGui.QApplication.translate("MainWindowSentence", "Zoom out", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_Out.setShortcut(QtGui.QApplication.translate("MainWindowSentence", "Ctrl+-", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddSentence.setText(QtGui.QApplication.translate("MainWindowSentence", "Add Sentence", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddSentence.setToolTip(QtGui.QApplication.translate("MainWindowSentence", "Add a new sentence", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddSentence.setShortcut(QtGui.QApplication.translate("MainWindowSentence", "Ctrl+Shift+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveSentence.setText(QtGui.QApplication.translate("MainWindowSentence", "Remove Sentence", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveSentence.setToolTip(QtGui.QApplication.translate("MainWindowSentence", "Remove sentence", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdateSentence.setText(QtGui.QApplication.translate("MainWindowSentence", "Update Sentence", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdateSentence.setToolTip(QtGui.QApplication.translate("MainWindowSentence", "Update actual sentence", None, QtGui.QApplication.UnicodeUTF8))

import sci_corpus_resource_rc
